card_types = dict(
    lands=dict(
        min_number=31,
        range=7,
    ),
    zero_mv_acc=dict(
        min_number=0,
        range=3,
    ),
    one_mv_acc=dict(
        min_number=10,
        range=8,
    ),
    one_mv_threat=dict(
        min_number=8,
        range=10,
    ),
    two_mv_threat=dict(
        min_number=10,
        range=8,
    ),
    three_mv_threat=dict(
        min_number=6,
        range=10,
    ),
    four_mv_threat=dict(
        min_number=5,
        range=10,
    ),
    five_mv_threat=dict(
        min_number=0,
        range=5,
    ),
    interaction=dict(
        min_number=5,
        range=10,
    )
)

decks_location = './decks.json'
